--[[
-- Copyright (c) 2026, GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007
-- @file   S001_css.lua
-- @brief  Global CSS by klbwui type (k*)
-- @note   Appearance: light (Windows XP Luna)
-- @note   Loaded by uires css_loader from skin dir (S000/S001/S002 sequential merge)
-- @history �?改历�?
--  \n 2026 创建; S00 拆出 klbwui type 全局 CSS (css_loader 字号阶�??)
--]]


local css_loader = require("klbcore.klbui.uires.css_loader")

local M = {}

local font_size_S = css_loader.font_size_S()
local font_size_M = css_loader.font_size_M()

M['global'] = {
	["type"] = {
		["kanimation"] = {
		},
		["kbtnex"] = {
			["check.font-size"] = font_size_M,
			["check.font-size:focus"] = font_size_M + 1,
			["check.stretch-image"] = "/scale9/button_background",
			["check.stretch-image:focus"] = "/scale9/button_background_focus",
			["stretch-image"] = "/scale9/button_background",
			["stretch-image:focus"] = "/scale9/button_background_focus",
		},
		["kbutton"] = {
			["padding-left"] = 2,
			["padding-right"] = 2,
			["text-align"] = "center",
			["text-align:disabled"] = "center",
			["text-align:focus"] = "center",
		},
		["kcalendar"] = {
			["border-color"] = {255, 127, 157, 185},
			["btn.stretch-image"] = "/scale9/calendar_btn_bg",
			["btn.stretch-image:focus"] = "/scale9/calendar_btn_bg_focus",
			["button_h"] = 36,
			["button_w"] = 44,
			["change_ym_h"] = 36,
			["change_ym_w"] = 40,
			["font-size"] = font_size_M,
			["font-size:disabled"] = font_size_M,
			["font-size:focus"] = font_size_M,
			["row_h"] = 36,
		},
		["kcheck"] = {
			["all-align"] = "left",
			["background-color"] = {255, 236, 233, 216},
			["background-color:disabled"] = {255, 236, 233, 216},
			["background-color:focus"] = {255, 236, 233, 216},
			["background-image"] = "/widgets/kcheck_off",
			["background-image:disabled"] = "/widgets/kcheck_off_disable",
			["background-image:focus"] = "/widgets/kcheck_off_focus",
			["border-width"] = {0, 0, 0, 0},
			["border-width:disabled"] = {0, 0, 0, 0},
			["border-width:focus"] = {0, 0, 0, 0},
			["check.background-color"] = {255, 236, 233, 216},
			["check.background-color:disabled"] = {255, 236, 233, 216},
			["check.background-color:focus"] = {255, 236, 233, 216},
			["check.background-image"] = "/widgets/kcheck_on",
			["check.background-image:disabled"] = "/widgets/kcheck_on_disable",
			["check.background-image:focus"] = "/widgets/kcheck_on_focus",
			["check.border-width"] = {0, 0, 0, 0},
			["check.border-width:disabled"] = {0, 0, 0, 0},
			["check.border-width:focus"] = {0, 0, 0, 0},
			["check.color"] = {255, 0, 0, 0},
			["check.color:disabled"] = {255, 172, 168, 153},
			["check.color:focus"] = {255, 0, 0, 0},
			["check.font-size"] = font_size_M,
			["check.font-size:disabled"] = font_size_M,
			["check.font-size:focus"] = font_size_M,
			["check.foreground-image"] = "/widgets/check_text_on",
			["check.foreground-image:disabled"] = "/widgets/check_text_on_disable",
			["check.foreground-image:focus"] = "/widgets/check_text_on_focus",
			["font-size"] = font_size_M,
			["font-size:disabled"] = font_size_M,
			["font-size:focus"] = font_size_M,
			["foreground-image"] = "/widgets/check_text_off",
			["foreground-image-height"] = 20,
			["foreground-image-width"] = 20,
			["foreground-image:disabled"] = "/widgets/check_text_off_disable",
			["foreground-image:focus"] = "/widgets/check_text_off_focus",
			["image-align"] = "left",
		},
		["kcombo"] = {
			["background-color"] = {255, 236, 233, 216},
			["background-color:focus"] = {255, 236, 233, 216},
			["padding-left"] = 2,
			["padding-right"] = 2,
		},
		["kdate"] = {
			["background-color"] = {255, 236, 233, 216},
			["background-color:disabled"] = {255, 192, 192, 192},
			["background-color:focus"] = {255, 236, 233, 216},
			["border-color"] = {255, 0, 0, 0},
			["border-color:focus"] = {255, 0, 0, 0},
			["border-width"] = {1, 1, 1, 1},
			["border-width:focus"] = {1, 1, 1, 1},
		},
		["kdemo"] = {
		},
		["kdialog"] = {
			["background-image"] = "/scale9/dialog_bg",
			["background-image-mode"] = "scale9",
		},
		["kdiv"] = {
		},
		["kedit"] = {
			["background-color"] = {255, 236, 233, 216},
			["background-color:focus"] = {255, 236, 233, 216},
		},
		["kgroup"] = {
		},
		["khscrollbar"] = {
		},
		["kip"] = {
		},
		["kline"] = {
		},
		["klist"] = {
			["append_class1"] = {
				["a1"] = {
					["background-color"] = {255, 26, 26, 26},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a10"] = {
					["check.foreground-image"] = "/config/cfg_chan_select_focus",
					["check.foreground-image:focus"] = "/config/cfg_chan_select_focus",
					["foreground-image"] = "/config/cfg_chan_select",
					["foreground-image:focus"] = "/config/cfg_chan_select_focus",
				},
				["a11"] = {
					["check.foreground-image"] = "/config/cfg_chan_focus",
					["check.foreground-image:focus"] = "/config/cfg_chan_focus",
					["foreground-image"] = "/config/cfg_chan",
					["foreground-image:focus"] = "/config/cfg_chan_focus",
				},
				["a12"] = {
					["background-color"] = {255, 32, 32, 61},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 255, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a13"] = {
					["background-color"] = {255, 32, 32, 61},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 255, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a14"] = {
					["check.foreground-image"] = "/config/cfg_list_set_select",
					["check.foreground-image:focus"] = "/config/cfg_list_set_select",
					["foreground-image"] = "/config/cfg_list_set_select",
					["foreground-image:focus"] = "/config/cfg_list_set_select",
				},
				["a15"] = {
					["check.foreground-image"] = "/config/cfg_list_set",
					["check.foreground-image:focus"] = "/config/cfg_list_set",
					["foreground-image"] = "/config/cfg_list_set",
					["foreground-image:focus"] = "/config/cfg_list_set",
				},
				["a16"] = {
					["check.foreground-image"] = "/config/cfg_list_delete_select",
					["check.foreground-image:focus"] = "/config/cfg_list_delete_select",
					["foreground-image"] = "/config/cfg_list_delete_select",
					["foreground-image:focus"] = "/config/cfg_list_delete_select",
				},
				["a17"] = {
					["check.foreground-image"] = "/config/cfg_list_delete",
					["check.foreground-image:focus"] = "/config/cfg_list_delete",
					["foreground-image"] = "/config/cfg_list_delete",
					["foreground-image:focus"] = "/config/cfg_list_delete",
				},
				["a2"] = {
					["check.stretch-image"] = "/scale9/button_blueground",
					["check.stretch-image:focus"] = "/scale9/button_blueground_focus",
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
					["stretch-image"] = "/scale9/button_blueground",
					["stretch-image:focus"] = "/scale9/button_blueground_focus",
				},
				["a3"] = {
					["background-color"] = {255, 26, 26, 26},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 255, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a4"] = {
					["background-color"] = {255, 26, 26, 26},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 255, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a5"] = {
					["background-color"] = {255, 32, 32, 61},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a6"] = {
					["foreground-image"] = "/config/cfg_play_select",
					["foreground-image:focus"] = "/config/cfg_play_select_focus",
				},
				["a7"] = {
					["foreground-image"] = "/config/cfg_play",
					["foreground-image:focus"] = "/config/cfg_play_focus",
				},
				["a8"] = {
					["foreground-image"] = "/config/cfg_log_info_select",
					["foreground-image:focus"] = "/config/cfg_log_info_select_focus",
				},
				["a9"] = {
					["foreground-image"] = "/config/cfg_log_info",
					["foreground-image:focus"] = "/config/cfg_log_info_focus",
				},
			},
			["append_class2"] = {
				["a1"] = {
					["background-color"] = {255, 26, 26, 26},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a10"] = {
					["check.foreground-image"] = "/config/cfg_chan_select_focus",
					["check.foreground-image:focus"] = "/config/cfg_chan_select_focus",
					["foreground-image"] = "/config/cfg_chan_select",
					["foreground-image:focus"] = "/config/cfg_chan_select_focus",
				},
				["a11"] = {
					["check.foreground-image"] = "/config/cfg_chan_focus",
					["check.foreground-image:focus"] = "/config/cfg_chan_focus",
					["foreground-image"] = "/config/cfg_chan",
					["foreground-image:focus"] = "/config/cfg_chan_focus",
				},
				["a12"] = {
					["background-color"] = {255, 32, 32, 61},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 255, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a13"] = {
					["background-color"] = {255, 32, 32, 61},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 255, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a14"] = {
					["check.foreground-image"] = "/config/cfg_list_set_select",
					["check.foreground-image:focus"] = "/config/cfg_list_set_select",
					["foreground-image"] = "/config/cfg_list_set_select",
					["foreground-image:focus"] = "/config/cfg_list_set_select",
				},
				["a15"] = {
					["check.foreground-image"] = "/config/cfg_list_set",
					["check.foreground-image:focus"] = "/config/cfg_list_set",
					["foreground-image"] = "/config/cfg_list_set",
					["foreground-image:focus"] = "/config/cfg_list_set",
				},
				["a16"] = {
					["check.foreground-image"] = "/config/cfg_list_delete_select",
					["check.foreground-image:focus"] = "/config/cfg_list_delete_select",
					["foreground-image"] = "/config/cfg_list_delete_select",
					["foreground-image:focus"] = "/config/cfg_list_delete_select",
				},
				["a17"] = {
					["check.foreground-image"] = "/config/cfg_list_delete",
					["check.foreground-image:focus"] = "/config/cfg_list_delete",
					["foreground-image"] = "/config/cfg_list_delete",
					["foreground-image:focus"] = "/config/cfg_list_delete",
				},
				["a2"] = {
					["check.stretch-image"] = "/scale9/button_blueground",
					["check.stretch-image:focus"] = "/scale9/button_blueground_focus",
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
					["stretch-image"] = "/scale9/button_blueground",
					["stretch-image:focus"] = "/scale9/button_blueground_focus",
				},
				["a3"] = {
					["background-color"] = {255, 26, 26, 26},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 255, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a4"] = {
					["background-color"] = {255, 26, 26, 26},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 255, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a5"] = {
					["background-color"] = {255, 32, 32, 61},
					["background-color:focus"] = {255, 26, 26, 26},
					["border-width"] = {0, 0, 0, 0},
					["color"] = {255, 0, 0, 0},
					["font-size"] = font_size_M,
					["font-size:focus"] = font_size_M,
				},
				["a6"] = {
					["foreground-image"] = "/config/cfg_play_select",
					["foreground-image:focus"] = "/config/cfg_play_select_focus",
				},
				["a7"] = {
					["foreground-image"] = "/config/cfg_play",
					["foreground-image:focus"] = "/config/cfg_play_focus",
				},
				["a8"] = {
					["foreground-image"] = "/config/cfg_log_info_select",
					["foreground-image:focus"] = "/config/cfg_log_info_select_focus",
				},
				["a9"] = {
					["foreground-image"] = "/config/cfg_log_info",
					["foreground-image:focus"] = "/config/cfg_log_info_focus",
				},
			},
			["head.height"] = 48,
			["head.static.arrows.color"] = {255, 180, 180, 180},
			["head.static.background-color"] = {255, 33, 33, 33},
			["head.static.color"] = {255, 200, 200, 200},
			["head.static.font-size"] = font_size_M,
			["head.static.text-align"] = "center",
			["hscrollbar.height"] = 20,
			["hscrollbar.middle_w"] = 150,
			["padding-left"] = 2,
			["padding-top"] = 2,
			["row.height"] = 36,
			["row1.background-color"] = {255, 26, 26, 26},
			["row2.background-color"] = {255, 26, 26, 26},
			["selectrow.background-color"] = {255, 32, 32, 61},
			["stretch-image"] = "/scale9/list_background",
			["vscrollbar.middle_h"] = 60,
			["vscrollbar.width"] = 20,
		},
		["klistex"] = {
			["font-size"] = font_size_M,
			["font-size:disabled"] = font_size_M,
			["font-size:focus"] = font_size_M,
			["head_h"] = 42,
			["row.font-size"] = font_size_S,
			["row.font-size:focus"] = font_size_S + 1,
			["row.text-align"] = "center",
			["row.text-align:focus"] = "center",
			["row_h"] = 32,
			["text-align"] = "center",
			["text-align:focus"] = "center",
			["vsc_w"] = 20,
		},
		["kmenu"] = {
		},
		["knum"] = {
			["background-color"] = {255, 236, 233, 216},
			["background-color:focus"] = {255, 236, 233, 216},
		},
		["kpassword"] = {
			["button-clear.foreground-image:focus"] = "/widgets/passwd_btn_clear_focus",
			["button.foreground-image-height"] = 20,
			["button.foreground-image-width"] = 20,
			["button.interval"] = 4,
			["button-symbol.foreground-image:focus"] = "/widgets/passwd_btn_symbol_focus",
		},
		["kpicture"] = {
			["border-width"] = {0, 0, 0, 0},
			["border-width:focus"] = {0, 0, 0, 0},
			["is_stretch"] = false,
		},
		["kprogress"] = {
			["color"] = {255, 49, 106, 197},
			["foreground-color"] = {255, 215, 215, 215},
			["foreground-height"] = 14,
			["max"] = 100,
			["min"] = 0,
		},
		["kqrcode"] = {
		},
		["kradio"] = {
		},
		["krichtext"] = {
			["background-color"] = {255, 236, 233, 216},
			["font-size"] = font_size_M,
		},
		["kslider"] = {
			["background-color"] = {255, 236, 233, 216},
			["background-color:disabled"] = {255, 236, 233, 216},
			["background-color:focus"] = {255, 236, 233, 216},
			["color"] = {255, 0, 84, 227},
			["color:disabled"] = {255, 127, 157, 185},
			["color:focus"] = {255, 0, 84, 227},
			["foreground-color"] = {255, 172, 168, 153},
			["foreground-color:disabled"] = {255, 172, 168, 153},
			["foreground-color:focus"] = {255, 172, 168, 153},
			["foreground-height"] = 6,
			["pos.height"] = 16,
			["pos.image"] = "/widgets/slider2",
			["pos.image:disabled"] = "/widgets/slider2_disable",
			["pos.image:focus"] = "/widgets/slider2_focus",
			["pos.width"] = 16,
		},
		["kspin"] = {
			["border-width"] = {1, 1, 1, 1},
			["border-width:disabled"] = {1, 1, 1, 1},
			["border-width:focus"] = {1, 1, 1, 1},
			["btn-bottom.foreground-image"] = "/widgets/numspin_btn_bottom",
			["btn-bottom.foreground-image-height"] = 15,
			["btn-bottom.foreground-image-width"] = 16,
			["btn-bottom.foreground-image:focus"] = "/widgets/numspin_btn_bottom_focus",
			["btn-top.foreground-image"] = "/widgets/numspin_btn_top",
			["btn-top.foreground-image-height"] = 15,
			["btn-top.foreground-image-width"] = 16,
			["btn-top.foreground-image:focus"] = "/widgets/numspin_btn_top_focus",
			["font-size"] = font_size_M - 1,
			["font-size:focus"] = font_size_M + 1,
			["max"] = 100,
			["min"] = 0,
			["value"] = 0,
		},
		["kstatic"] = {
			["background-color"] = {255, 236, 233, 216},
			["border-width"] = {0, 0, 0, 0},
			["text-align"] = "right",
		},
		["ktab"] = {
			["background-color"] = {255, 236, 233, 216},
			["border-width"] = {0, 0, 0, 0},
			["button.background-color"] = {255, 236, 233, 216},
			["button.background-color:focus"] = {255, 236, 233, 216},
			["button.color"] = {255, 0, 0, 0},
			["button.color:focus"] = {255, 49, 106, 197},
			["button.font-size"] = font_size_M,
			["button.font-size:focus"] = font_size_M,
			["button.height"] = 34,
			["button.padding"] = {4, 4, 4, 4},
			["button.text-align"] = "center",
			["button.text-align:focus"] = "center",
			["button.width-max"] = 400,
			["button.width-min"] = 120,
			["check.background-color"] = {255, 49, 106, 197},
			["check.height"] = 2,
			["head.background-color"] = {255, 236, 233, 216},
			["head_line.background-color"] = {255, 41, 41, 41},
			["head_line.height"] = 1,
			["interval_x"] = 10,
			["interval_y"] = 10,
			["stretch-image"] = "/scale9/tab_background",
		},
		["kticker"] = {
		},
		["ktime"] = {
		},
		["kview"] = {
			["background-color"] = {255, 236, 233, 216},
			["border-width"] = {0, 0, 0, 0},
			["border-width:disabled"] = {0, 0, 0, 0},
			["border-width:focus"] = {0, 0, 0, 0},
		},
		["kvscrollbar"] = {
		},
		["kvslider"] = {
			["background-color"] = {255, 236, 233, 216},
			["background-color:disabled"] = {255, 236, 233, 216},
			["background-color:focus"] = {255, 236, 233, 216},
			["color"] = {255, 0, 84, 227},
			["color:disabled"] = {255, 0, 84, 227},
			["color:focus"] = {255, 0, 84, 227},
			["foreground-color"] = {255, 172, 168, 153},
			["foreground-color:disabled"] = {255, 172, 168, 153},
			["foreground-color:focus"] = {255, 172, 168, 153},
			["foreground-width"] = 6,
			["thumb.height"] = 16,
			["thumb.image"] = "/widgets/slider",
			["thumb.image:focus"] = "/widgets/slider_focus",
			["thumb.width"] = 16,
		},
	},
}

return M
