--[[
-- Copyright (c) 2026, GNU LESSER GENERAL PUBLIC LICENSE Version 3, 29 June 2007
-- @file   registry_ch2.lua
-- @brief  lua_test 第 2 章 (kpfs) 用例表
-- @note   约定 **klua-test-design**; 由 registry.lua 聚合
-- @history 修改历史
--  \n 2026 创建文件
--]]


local M = {}

M.chapter = 2
M.title = "Chapter 2 kpfs"

M.cases = {
	{
		doc_id = "2.1.1",
		ids = { "kpfs.version", "pfs.version" },
		mod = "lua_test.pfs.probe.ch2_s1_1",
		desc = "kpfs.version smoke test",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_probe.md",
		chapter = 2,
		batch_ok = true,
	},
	{
		doc_id = "2.1.2",
		ids = { "kpfs.probe.all", "pfs.probe.all", "pfs.probe" },
		mod = "lua_test.pfs.probe.ch2_s1_2",
		desc = "kpfs.image.create + kpfs.probe.all smoke test",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_probe.md",
		chapter = 2,
		batch_ok = true,
	},
	{
		doc_id = "2.1.3",
		ids = { "kpfs.probe.part", "pfs.probe.part" },
		mod = "lua_test.pfs.probe.ch2_s1_3",
		desc = "kpfs.image + disk.mkpt + kpfs.probe.part smoke test",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_probe.md",
		chapter = 2,
		batch_ok = true,
	},
	{
		doc_id = "2.1.4",
		ids = { "kpfs.probe.fs", "pfs.probe.fs" },
		mod = "lua_test.pfs.probe.ch2_s1_4",
		desc = "kpfs.image + disk.mkpt/mkfs + kpfs.probe.fs smoke test",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_probe.md",
		chapter = 2,
		batch_ok = true,
	},
	{
		doc_id = "2.2.1",
		ids = { "kpfs.image", "pfs.image" },
		mod = "lua_test.pfs.make.ch2_s2_1",
		desc = "kpfs.image.create dynamic vhdx + image.info",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.2.2",
		ids = { "kpfs.image.vhd", "pfs.image.vhd" },
		mod = "lua_test.pfs.make.ch2_s2_2",
		desc = "kpfs.image.create dynamic vhd + image.info",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.2.3",
		ids = { "kpfs.image.fixed", "pfs.image.fixed" },
		mod = "lua_test.pfs.make.ch2_s2_3",
		desc = "kpfs.image.create fixed vhdx + image.info size",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.2.4",
		ids = { "kpfs.image.vhd_fixed", "pfs.image.vhd_fixed" },
		mod = "lua_test.pfs.make.ch2_s2_4",
		desc = "kpfs.image.create fixed vhd + image.info",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.2.5",
		ids = { "kpfs.mkpt", "pfs.mkpt" },
		mod = "lua_test.pfs.make.ch2_s2_5",
		desc = "kpfs.image + disk.mkpt + kpfs.probe.part",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.2.6",
		ids = { "kpfs.mkfs", "pfs.mkfs" },
		mod = "lua_test.pfs.make.ch2_s2_6",
		desc = "kpfs.image + disk.mkpt/mkfs + kpfs.probe.fs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.2.7",
		ids = { "kpfs.mkvol", "pfs.mkvol" },
		mod = "lua_test.pfs.make.ch2_s2_7",
		desc = "kpfs.image + disk.mkvol + probe.fs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_make.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.1",
		ids = { "kpfs.mount", "pfs.mount" },
		mod = "lua_test.pfs.mount.ch2_s3_1",
		desc = "kpfs.mount / umount smoke test",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.2",
		ids = { "kpfs.remount", "pfs.remount" },
		mod = "lua_test.pfs.mount.ch2_s3_2",
		desc = "remount ro<->rw",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.3",
		ids = { "kpfs.vfs.ro_write", "pfs.vfs.ro_write" },
		mod = "lua_test.pfs.mount.ch2_s3_3",
		desc = "write on ro mount",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.4",
		ids = { "kpfs.vfs.umount_flow", "pfs.vfs.umount_flow" },
		mod = "lua_test.pfs.mount.ch2_s3_4",
		desc = "explicit umount flow (UMOUNT_FLOW)",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.5",
		ids = { "kpfs.mount.rw", "pfs.mount.rw" },
		mod = "lua_test.pfs.mount.ch2_s3_5",
		desc = "explicit rw mount + write",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.6",
		ids = { "kpfs.mount.part_mode", "pfs.mount.part_mode" },
		mod = "lua_test.pfs.mount.ch2_s3_6",
		desc = "mount by per-part mode array",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.7",
		ids = { "kpfs.mount.opts", "pfs.mount.opts" },
		mod = "lua_test.pfs.mount.ch2_s3_7",
		desc = "mount opts offset / sector_size",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.8",
		ids = { "kpfs.remount.part", "pfs.remount.part" },
		mod = "lua_test.pfs.mount.ch2_s3_8",
		desc = "remount single partition",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.9",
		ids = { "kpfs.umount.part", "pfs.umount.part" },
		mod = "lua_test.pfs.mount.ch2_s3_9",
		desc = "umount single partition / batch",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.10",
		ids = { "kpfs.mount.eexist", "pfs.mount.eexist" },
		mod = "lua_test.pfs.mount.ch2_s3_10",
		desc = "duplicate mount same disk name",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.11",
		ids = { "kpfs.mount.probe_ok", "pfs.mount.probe_ok" },
		mod = "lua_test.pfs.mount.ch2_s3_11",
		desc = "probe.all after mount",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.3.12",
		ids = { "kpfs.mount.bad_vol", "pfs.mount.bad_vol" },
		mod = "lua_test.pfs.mount.ch2_s3_12",
		desc = "bad volume mount fail (SINGLE_ONLY)",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mount.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.1",
		ids = { "kpfs.vfs.open", "pfs.vfs.open" },
		mod = "lua_test.pfs.file.ch2_s4_1",
		desc = "vfs.open create missing file",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.2",
		ids = { "kpfs.vfs.read", "pfs.vfs.read" },
		mod = "lua_test.pfs.file.ch2_s4_2",
		desc = "vfs read existing file",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.3",
		ids = { "kpfs.vfs.seek", "pfs.vfs.seek" },
		mod = "lua_test.pfs.file.ch2_s4_3",
		desc = "seek / tell / truncate",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.4",
		ids = { "kpfs.vfs.write", "pfs.vfs.write" },
		mod = "lua_test.pfs.file.ch2_s4_4",
		desc = "overwrite existing file",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.5",
		ids = { "kpfs.vfs.open.enoent", "pfs.vfs.open.enoent" },
		mod = "lua_test.pfs.file.ch2_s4_5",
		desc = "open missing path negative",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.6",
		ids = { "kpfs.vfs.open.mode", "pfs.vfs.open.mode" },
		mod = "lua_test.pfs.file.ch2_s4_6",
		desc = "open modes r+ / a / a+",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.7",
		ids = { "kpfs.vfs.read.chunk", "pfs.vfs.read.chunk" },
		mod = "lua_test.pfs.file.ch2_s4_7",
		desc = "chunked read(n)",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.8",
		ids = { "kpfs.vfs.empty", "pfs.vfs.empty" },
		mod = "lua_test.pfs.file.ch2_s4_8",
		desc = "empty file CREAT",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.9",
		ids = { "kpfs.vfs.truncate.extend", "pfs.vfs.truncate.extend" },
		mod = "lua_test.pfs.file.ch2_s4_9",
		desc = "truncate extend",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.10",
		ids = { "kpfs.vfs.seek.bad", "pfs.vfs.seek.bad" },
		mod = "lua_test.pfs.file.ch2_s4_10",
		desc = "invalid seek / EOF seek",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.11",
		ids = { "kpfs.vfs.error", "pfs.vfs.error" },
		mod = "lua_test.pfs.file.ch2_s4_11",
		desc = "f:error() stream error query",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.4.12",
		ids = { "kpfs.vfs.fsync", "pfs.vfs.fsync" },
		mod = "lua_test.pfs.file.ch2_s4_12",
		desc = "fsync persist (UMOUNT_FLOW)",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_file.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.1",
		ids = { "kpfs.vfs.path.mkdir", "pfs.vfs.path.mkdir" },
		mod = "lua_test.pfs.path.ch2_s5_1",
		desc = "mkdir 3-level dir and write file",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.2",
		ids = { "kpfs.vfs.path.opendir", "pfs.vfs.path.opendir" },
		mod = "lua_test.pfs.path.ch2_s5_2",
		desc = "opendir directory listing",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.3",
		ids = { "kpfs.vfs.path", "pfs.vfs.path" },
		mod = "lua_test.pfs.path.ch2_s5_3",
		desc = "path access/rename/unlink/rmdir",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.4",
		ids = { "kpfs.vfs.copy", "pfs.vfs.copy" },
		mod = "lua_test.pfs.path.ch2_s5_4",
		desc = "copy single file within volume",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.5",
		ids = { "kpfs.vfs.copy.host", "pfs.vfs.copy.host" },
		mod = "lua_test.pfs.path.ch2_s5_5",
		desc = "copy host<->volume @ path",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.6",
		ids = { "kpfs.vfs.copy.cross", "pfs.vfs.copy.cross" },
		mod = "lua_test.pfs.path.ch2_s5_6",
		desc = "copy cross-partition",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.7",
		ids = { "kpfs.vfs.remove", "pfs.vfs.remove" },
		mod = "lua_test.pfs.path.ch2_s5_7",
		desc = "remove file / empty dir",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.8",
		ids = { "kpfs.vfs.path.neg", "pfs.vfs.path.neg" },
		mod = "lua_test.pfs.path.ch2_s5_8",
		desc = "path negative cases",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.9",
		ids = { "kpfs.vfs.rename.cross", "pfs.vfs.rename.cross" },
		mod = "lua_test.pfs.path.ch2_s5_9",
		desc = "cross-partition rename",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.10",
		ids = { "kpfs.vfs.opendir.neg", "pfs.vfs.opendir.neg" },
		mod = "lua_test.pfs.path.ch2_s5_10",
		desc = "opendir negative and direrror",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.11",
		ids = { "kpfs.vfs.opendir.full", "pfs.vfs.opendir.full" },
		mod = "lua_test.pfs.path.ch2_s5_11",
		desc = "root and subdir listing",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.5.12",
		ids = { "kpfs.vfs.name.utf8", "pfs.vfs.name.utf8" },
		mod = "lua_test.pfs.path.ch2_s5_12",
		desc = "UTF-8 filename",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_path.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.1",
		ids = { "kpfs.mtd.raw", "pfs.mtd.raw" },
		mod = "lua_test.pfs.mtd.ch2_s6_1",
		desc = "mtd.raw.create",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.2",
		ids = { "kpfs.mtd.mkfs", "pfs.mtd.mkfs" },
		mod = "lua_test.pfs.mtd.ch2_s6_2",
		desc = "mtd.mkfs squashfs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.3",
		ids = { "kpfs.mtd.mkvol", "pfs.mtd.mkvol" },
		mod = "lua_test.pfs.mtd.ch2_s6_3",
		desc = "mtd.mkvol romfs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.4",
		ids = { "kpfs.mtd.mkfs.ubifs", "pfs.mtd.mkfs.ubifs" },
		mod = "lua_test.pfs.mtd.ch2_s6_4",
		desc = "mtd.mkfs ubifs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.5",
		ids = { "kpfs.mtd.mkvol.jffs2", "pfs.mtd.mkvol.jffs2" },
		mod = "lua_test.pfs.mtd.ch2_s6_5",
		desc = "mtd.mkvol jffs2",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.6",
		ids = { "kpfs.mtd.ubi", "pfs.mtd.ubi" },
		mod = "lua_test.pfs.mtd.ch2_s6_6",
		desc = "mtd.ubi.create",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.7",
		ids = { "kpfs.mtd.mkvol.squashfs", "pfs.mtd.mkvol.squashfs" },
		mod = "lua_test.pfs.mtd.ch2_s6_7",
		desc = "mtd.mkvol squashfs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.8",
		ids = { "kpfs.mtd.mkfs.romfs", "pfs.mtd.mkfs.romfs" },
		mod = "lua_test.pfs.mtd.ch2_s6_8",
		desc = "mtd.mkfs romfs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.9",
		ids = { "kpfs.mtd.mkvol.ubifs", "pfs.mtd.mkvol.ubifs" },
		mod = "lua_test.pfs.mtd.ch2_s6_9",
		desc = "mtd.mkvol ubifs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.10",
		ids = { "kpfs.mtd.disk_mkfs.neg", "pfs.mtd.disk_mkfs.neg" },
		mod = "lua_test.pfs.mtd.ch2_s6_10",
		desc = "disk.mkfs format MTD FS forbidden",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.11",
		ids = { "kpfs.mtd.mkfs.jffs2", "pfs.mtd.mkfs.jffs2" },
		mod = "lua_test.pfs.mtd.ch2_s6_11",
		desc = "mtd.mkfs jffs2",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.12",
		ids = { "kpfs.mtd.mkfs.multi", "pfs.mtd.mkfs.multi" },
		mod = "lua_test.pfs.mtd.ch2_s6_12",
		desc = "multi-partition mtd.mkfs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.13",
		ids = { "kpfs.mtd.mkfs.yaffs", "pfs.mtd.mkfs.yaffs" },
		mod = "lua_test.pfs.mtd.ch2_s6_13",
		desc = "mtd.mkfs yaffs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.14",
		ids = { "kpfs.mtd.mkvol.yaffs", "pfs.mtd.mkvol.yaffs" },
		mod = "lua_test.pfs.mtd.ch2_s6_14",
		desc = "mtd.mkvol yaffs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.15",
		ids = { "kpfs.mtd.mkfs.erofs", "pfs.mtd.mkfs.erofs" },
		mod = "lua_test.pfs.mtd.ch2_s6_15",
		desc = "mtd.mkfs erofs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.16",
		ids = { "kpfs.mtd.mkvol.erofs", "pfs.mtd.mkvol.erofs" },
		mod = "lua_test.pfs.mtd.ch2_s6_16",
		desc = "mtd.mkvol erofs empty tree",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.17",
		ids = { "kpfs.mtd.mkfs.cramfs", "pfs.mtd.mkfs.cramfs" },
		mod = "lua_test.pfs.mtd.ch2_s6_17",
		desc = "mtd.mkfs cramfs",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.18",
		ids = { "kpfs.mtd.mkvol.cramfs", "pfs.mtd.mkvol.cramfs" },
		mod = "lua_test.pfs.mtd.ch2_s6_18",
		desc = "mtd.mkvol cramfs empty tree",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.19",
		ids = { "kpfs.mtd.raw.neg", "pfs.mtd.raw.neg" },
		mod = "lua_test.pfs.mtd.ch2_s6_19",
		desc = "raw.create misaligned size negative",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
	{
		doc_id = "2.6.20",
		ids = { "kpfs.mtd.mkvol.multi", "pfs.mtd.mkvol.multi" },
		mod = "lua_test.pfs.mtd.ch2_s6_20",
		desc = "mtd.mkvol multi-partition + label",
		doc = "klua_doc/lua/lua_test/kpfs/kpfs_mtd.md",
		chapter = 2,
		batch_ok = false,
	},
}

return M
